# The authoritative section list, parsed from the table of contents.
# Format: (section_number, section_title, chapter_roman, chapter_name)
SECTIONS = [
    # Chapter I - Preliminary
    ("1", "Short title, extent and commencement", "I", "Preliminary"),
    ("2", "Definitions", "I", "Preliminary"),
    ("3", "Power to add to or omit from the list of psychotropic substances", "I", "Preliminary"),
    # Chapter II - Authorities and Officers
    ("4", "Central Government to take measures for preventing and combating abuse of and illicit traffic in narcotic drugs, etc.", "II", "Authorities and Officers"),
    ("5", "Officers of Central Government", "II", "Authorities and Officers"),
    ("6", "The Narcotic Drugs and Psychotropic Substances Consultative Committee", "II", "Authorities and Officers"),
    ("7", "Officers of State Government", "II", "Authorities and Officers"),
    # Chapter IIA
    ("7A", "National Fund for Control of Drug Abuse", "IIA", "National Fund for Control of Drug Abuse"),
    ("7B", "Annual report of activities financed under the Fund", "IIA", "National Fund for Control of Drug Abuse"),
    # Chapter III - Prohibition, Control and Regulation
    ("8", "Prohibition of certain operations", "III", "Prohibition, Control and Regulation"),
    ("8A", "Prohibition of certain activities relating to property derived from offence", "III", "Prohibition, Control and Regulation"),
    ("9", "Power of Central Government to permit, control and regulate", "III", "Prohibition, Control and Regulation"),
    ("9A", "Power to control and regulate controlled substances", "III", "Prohibition, Control and Regulation"),
    ("10", "Power of State Government to permit, control and regulate", "III", "Prohibition, Control and Regulation"),
    ("11", "Narcotic drugs and psychotropic substances, etc., not liable to distress or attachment", "III", "Prohibition, Control and Regulation"),
    ("12", "Restrictions over external dealings in narcotic drugs and psychotropic substances", "III", "Prohibition, Control and Regulation"),
    ("13", "Special provisions relating to coca plant and coca leaves for use in the preparation of flavouring agent", "III", "Prohibition, Control and Regulation"),
    ("14", "Special provision relating to cannabis", "III", "Prohibition, Control and Regulation"),
    # Chapter IV - Offences and Penalties
    ("15", "Punishment for contravention in relation to poppy straw", "IV", "Offences and Penalties"),
    ("16", "Punishment for contravention in relation to coca plant and coca leaves", "IV", "Offences and Penalties"),
    ("17", "Punishment for contravention in relation to prepared opium", "IV", "Offences and Penalties"),
    ("18", "Punishment for contravention in relation to opium poppy and opium", "IV", "Offences and Penalties"),
    ("19", "Punishment for embezzlement of opium by cultivator", "IV", "Offences and Penalties"),
    ("20", "Punishment for contravention in relation to cannabis plant and cannabis", "IV", "Offences and Penalties"),
    ("21", "Punishment for contravention in relation to manufactured drugs and preparations", "IV", "Offences and Penalties"),
    ("22", "Punishment for contravention in relation to psychotropic substances", "IV", "Offences and Penalties"),
    ("23", "Punishment for illegal import into India, export from India or transhipment of narcotic drugs and psychotropic substances", "IV", "Offences and Penalties"),
    ("24", "Punishment for external dealings in narcotic drugs and psychotropic substances in contravention of section 12", "IV", "Offences and Penalties"),
    ("25", "Punishment for allowing premises, etc., to be used for commission of an offence", "IV", "Offences and Penalties"),
    ("25A", "Punishment for contravention of orders made under section 9A", "IV", "Offences and Penalties"),
    ("26", "Punishment for certain acts by licensee or his servants", "IV", "Offences and Penalties"),
    ("27", "Punishment for consumption of any narcotic drug or psychotropic substance", "IV", "Offences and Penalties"),
    ("27A", "Punishment for financing illicit traffic and harbouring offenders", "IV", "Offences and Penalties"),
    ("27B", "Punishment for contravention of section 8A", "IV", "Offences and Penalties"),
    ("28", "Punishment for attempts to commit offences", "IV", "Offences and Penalties"),
    ("29", "Punishment for abetment and criminal conspiracy", "IV", "Offences and Penalties"),
    ("30", "Preparation", "IV", "Offences and Penalties"),
    ("31", "Enhanced punishment for offences after previous conviction", "IV", "Offences and Penalties"),
    ("31A", "Death penalty for certain offences after previous conviction", "IV", "Offences and Penalties"),
    ("32", "Punishment for offence for which no punishment is provided", "IV", "Offences and Penalties"),
    ("32A", "No suspension, remission or commutation in any sentence awarded under this Act", "IV", "Offences and Penalties"),
    ("32B", "Factors to be taken into account for imposing higher than the minimum punishment", "IV", "Offences and Penalties"),
    ("33", "Application of section 360 of the Code of Criminal Procedure, 1973 and of the Probation of Offenders Act, 1958", "IV", "Offences and Penalties"),
    ("34", "Security for abstaining from commission of offence", "IV", "Offences and Penalties"),
    ("35", "Presumption of culpable mental state", "IV", "Offences and Penalties"),
    ("36", "Constitution of Special Court", "IV", "Offences and Penalties"),
    ("36A", "Offences triable by Special Courts", "IV", "Offences and Penalties"),
    ("36B", "Appeal and revision", "IV", "Offences and Penalties"),
    ("36C", "Application of Code to proceedings before a Special Court", "IV", "Offences and Penalties"),
    ("36D", "Transitional provisions", "IV", "Offences and Penalties"),
    ("37", "Offences to be cognizable and non-bailable", "IV", "Offences and Penalties"),
    ("38", "Offences by companies", "IV", "Offences and Penalties"),
    ("39", "Power of court to release certain offenders on probation", "IV", "Offences and Penalties"),
    ("40", "Power of court to publish names, place of business, etc., of certain offenders", "IV", "Offences and Penalties"),
    # Chapter V - Procedure
    ("41", "Power to issue warrant and authorisation", "V", "Procedure"),
    ("42", "Power of entry, search, seizure and arrest without warrant or authorisation", "V", "Procedure"),
    ("43", "Power of seizure and arrest in public place", "V", "Procedure"),
    ("44", "Power of entry, search, seizure and arrest in offences relating to coca plant, opium poppy and cannabis plant", "V", "Procedure"),
    ("45", "Procedure where seizure of goods liable to confiscation not practicable", "V", "Procedure"),
    ("46", "Duty of land holder to give information of illegal cultivation", "V", "Procedure"),
    ("47", "Duty of certain officers to give information of illegal cultivation", "V", "Procedure"),
    ("48", "Power of attachment of crop illegally cultivated", "V", "Procedure"),
    ("49", "Power to stop and search conveyance", "V", "Procedure"),
    ("50", "Conditions under which search of persons shall be conducted", "V", "Procedure"),
    ("50A", "Power to undertake controlled delivery", "V", "Procedure"),
    ("51", "Provisions of the Code of Criminal Procedure, 1973 to apply to warrants, arrests, searches and seizures", "V", "Procedure"),
    ("52", "Disposal of persons arrested and articles seized", "V", "Procedure"),
    ("52A", "Disposal of seized narcotic drugs and psychotropic substances", "V", "Procedure"),
    ("53", "Power to invest officers of certain departments with powers of an officer-in-charge of a police station", "V", "Procedure"),
    ("53A", "Relevancy of statements under certain circumstances", "V", "Procedure"),
    ("54", "Presumption from possession of illicit articles", "V", "Procedure"),
    ("55", "Police to take charge of articles seized and delivered", "V", "Procedure"),
    ("56", "Obligation of officers to assist each other", "V", "Procedure"),
    ("57", "Report of arrest and seizure", "V", "Procedure"),
    ("57A", "Report of seizure of property of the person arrested by the notified officer", "V", "Procedure"),
    ("58", "Punishment for vexatious entry, search, seizure or arrest", "V", "Procedure"),
    ("59", "Failure of officer in duty or his connivance at the contravention of the provisions of this Act", "V", "Procedure"),
    ("60", "Liability of illicit drugs, substances, plants, articles and conveyances to confiscation", "V", "Procedure"),
    ("61", "Confiscation of goods used for concealing illicit drugs or substances", "V", "Procedure"),
    ("62", "Confiscation of sale proceeds of illicit drugs or substances", "V", "Procedure"),
    ("63", "Procedure in making confiscations", "V", "Procedure"),
    ("64", "Power to tender immunity from prosecution", "V", "Procedure"),
    ("64A", "Immunity from prosecution to addicts volunteering for treatment", "V", "Procedure"),
    ("65", "[Omitted]", "V", "Procedure"),
    ("66", "Presumption as to documents in certain cases", "V", "Procedure"),
    ("67", "Power to call for information, etc.", "V", "Procedure"),
    ("68", "Information as to commission of offences", "V", "Procedure"),
    # Chapter VA - Forfeiture of Illegally Acquired Property
    ("68A", "Application", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68B", "Definitions", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68C", "Prohibition of holding illegally acquired property", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68D", "Competent authority", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68E", "Identifying illegally acquired property", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68F", "Seizure or freezing of illegally acquired property", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68G", "Management of properties seized or forfeited under this Chapter", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68H", "Notice of forfeiture of property", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68I", "Forfeiture of property in certain cases", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68J", "Burden of proof", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68K", "Fine in lieu of forfeiture", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68L", "Procedure in relation to certain trust properties", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68M", "Certain transfers to be null and void", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68N", "Constitution of Appellate Tribunal", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68O", "Appeals", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68P", "Notice or order not to be invalid for error in description", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68Q", "Bar of jurisdiction", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68R", "Competent authority and Appellate Tribunal to have powers of civil court", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68S", "Information to competent authority", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68T", "Certain officers to assist Administrator, competent authority and Appellate Tribunal", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68U", "Power to take possession", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68V", "Rectification of mistakes", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68W", "Findings under other laws not conclusive for proceedings under this Chapter", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68X", "Service of notices and orders", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68Y", "Punishment for acquiring property in relation to which proceedings have been taken, under this Chapter", "VA", "Forfeiture of Illegally Acquired Property"),
    ("68Z", "Release of property in certain cases", "VA", "Forfeiture of Illegally Acquired Property"),
    # Chapter VI - Miscellaneous
    ("69", "Protection of action taken in good faith", "VI", "Miscellaneous"),
    ("70", "Central Government and State Government to have regard to international conventions while making rules", "VI", "Miscellaneous"),
    ("71", "Power of Government to establish centres for identification, treatment, etc., of addicts and for supply of narcotic drug and psychotropic substances", "VI", "Miscellaneous"),
    ("72", "Recovery of sums due to Government", "VI", "Miscellaneous"),
    ("73", "Bar of jurisdiction", "VI", "Miscellaneous"),
    ("74", "Transitional provisions", "VI", "Miscellaneous"),
    ("74A", "Power of Central Government to give directions", "VI", "Miscellaneous"),
    ("75", "Power to delegate", "VI", "Miscellaneous"),
    ("76", "Power of Central Government to make rules", "VI", "Miscellaneous"),
    ("77", "Rules and notifications to be laid before Parliament", "VI", "Miscellaneous"),
    ("78", "Power of State Government to make rules", "VI", "Miscellaneous"),
    ("79", "Application of the Customs Act, 1962", "VI", "Miscellaneous"),
    ("80", "Application of the Drugs and Cosmetics Act, 1940 not barred", "VI", "Miscellaneous"),
    ("81", "Saving of State and special laws", "VI", "Miscellaneous"),
    ("82", "Repeal and savings", "VI", "Miscellaneous"),
    ("83", "Power to remove difficulties", "VI", "Miscellaneous"),
]
